# Generated by Django 4.1.3 on 2022-11-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='birhtdate',
            new_name='birthdate',
        ),
    ]
